// backend/resources/js/Pages/parkirgo/Audit.vue
<script>
import Layout from "@/Layouts/main.vue";
import PageHeader from "@/Components/page-header.vue";

export default {
  components: { Layout, PageHeader },
  props: {
    logs: { type: Object, default: () => ({ data: [] }) },
  },
  methods: {
    formatDate(value) {
      if (!value) return "-";
      return new Intl.DateTimeFormat("id-ID", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date(value));
    },
    actionClass(action) {
      const actionText = (action || "").toLowerCase();
      if (actionText.includes("create") || actionText.includes("buat")) return "success";
      if (actionText.includes("update") || actionText.includes("ubah")) return "warning";
      if (actionText.includes("delete") || actionText.includes("hapus")) return "danger";
      if (actionText.includes("login")) return "primary";
      return "secondary";
    },
  },
};
</script>

<template>
  <Layout>
    <PageHeader title="Audit Log" pageTitle="ParkirGo" />

    <BRow class="g-3 mb-4">
      <BCol md="4">
        <BCard no-body class="border-0 shadow-sm stat-card">
          <BCardBody>
            <div class="d-flex align-items-center justify-content-between">
              <div>
                <p class="text-muted mb-1">Total Aktivitas</p>
                <h3 class="mb-0">{{ logs.total || logs.data?.length || 0 }}</h3>
              </div>
              <div class="avatar-sm rounded-circle bg-primary-subtle text-primary d-flex align-items-center justify-content-center">
                <i class="ri-history-line fs-22"></i>
              </div>
            </div>
          </BCardBody>
        </BCard>
      </BCol>
    </BRow>

    <BCard no-body class="border-0 shadow-sm">
      <BCardHeader>
        <BCardTitle class="mb-1">Riwayat Aktivitas Sistem</BCardTitle>
        <p class="text-muted mb-0">Pantau perubahan data dan aktivitas penting pada ParkirGo.</p>
      </BCardHeader>
      <BCardBody>
        <div class="table-responsive table-card">
          <table class="table table-hover align-middle mb-0">
            <thead class="table-light">
              <tr>
                <th>Waktu</th>
                <th>Pengguna</th>
                <th>Aksi</th>
                <th>Entitas</th>
                <th>ID Entitas</th>
                <th>IP Address</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="log in logs.data" :key="log.id">
                <td>{{ formatDate(log.created_at) }}</td>
                <td>
                  <div class="fw-semibold">{{ log.user?.name || 'Sistem' }}</div>
                  <small class="text-muted">{{ log.user?.email || '-' }}</small>
                </td>
                <td><span :class="`badge bg-${actionClass(log.action)}-subtle text-${actionClass(log.action)}`">{{ log.action }}</span></td>
                <td>{{ log.entity_type || '-' }}</td>
                <td>{{ log.entity_id || '-' }}</td>
                <td>{{ log.ip_address || '-' }}</td>
              </tr>
              <tr v-if="!logs.data?.length">
                <td colspan="6" class="text-center text-muted py-4">Belum ada audit log.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </BCardBody>
    </BCard>
  </Layout>
</template>

<style scoped>
.stat-card { transition: transform .2s ease, box-shadow .2s ease; }
.stat-card:hover { transform: translateY(-3px); box-shadow: 0 18px 45px rgba(15, 23, 42, .12) !important; }
.avatar-sm { width: 48px; height: 48px; }
</style>

// parkirgo-admin/src/app/(parkirgo)/audit/page.tsx
"use client";

import React, { useEffect, useState } from "react";
import {
  Card,
  CardBody,
  CardHeader,
  Col,
  Row,
  Table,
  Spinner,
  Button,
  Input,
} from "reactstrap";

const AuditPage = () => {
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState({
    dateFrom: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    dateTo: new Date().toISOString().split("T")[0],
    entityType: "",
    action: "",
  });
  const [pagination, setPagination] = useState({
    page: 1,
    totalPages: 1,
    total: 0,
  });

  useEffect(() => {
    fetchLogs();
  }, [filter, pagination.page]);

  const fetchLogs = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams({
        page: pagination.page.toString(),
        limit: "50",
        ...(filter.dateFrom && { dateFrom: filter.dateFrom }),
        ...(filter.dateTo && { dateTo: filter.dateTo }),
        ...(filter.entityType && { entityType: filter.entityType }),
        ...(filter.action && { action: filter.action }),
      });

      const res = await fetch(`/api/audit-logs?${params}`);
      const data = await res.json();
      if (data.success) {
        setLogs(data.data);
        setPagination((prev) => ({
          ...prev,
          totalPages: data.pagination.totalPages,
          total: data.pagination.total,
        }));
      }
    } catch (error) {
      console.error("Error fetching logs:", error);
    } finally {
      setLoading(false);
    }
  };

  const formatDateTime = (date: string) => {
    return new Date(date).toLocaleString("id-ID", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  };

  const getActionBadgeColor = (action: string) => {
    if (action.includes("DELETE")) return "danger";
    if (action.includes("CREATE")) return "success";
    if (action.includes("UPDATE")) return "primary";
    if (action.includes("VERIFY")) return "info";
    if (action.includes("REJECT")) return "warning";
    return "secondary";
  };

  return (
    <div className="page-content">
      <div className="container-fluid">
        <div className="row">
          <div className="col-12">
            <div className="page-title-box">
              <h4 className="mb-0 font-size-18">Log Audit Sistem</h4>
            </div>
          </div>
        </div>

        {/* Filters */}
        <Row className="mb-3">
          <Col md={2}>
            <Input
              type="date"
              value={filter.dateFrom}
              onChange={(e) =>
                setFilter({ ...filter, dateFrom: e.target.value })
              }
              placeholder="Dari Tanggal"
            />
          </Col>
          <Col md={2}>
            <Input
              type="date"
              value={filter.dateTo}
              onChange={(e) =>
                setFilter({ ...filter, dateTo: e.target.value })
              }
              placeholder="Sampai Tanggal"
            />
          </Col>
          <Col md={2}>
            <Input
              type="select"
              value={filter.entityType}
              onChange={(e) =>
                setFilter({ ...filter, entityType: e.target.value })
              }
            >
              <option value="">Semua Entitas</option>
              <option value="User">Pengguna</option>
              <option value="Zone">Zona</option>
              <option value="ZoneTariff">Tarif</option>
              <option value="ZonePenalty">Denda</option>
              <option value="Transaction">Transaksi</option>
            </Input>
          </Col>
          <Col md={2}>
            <Input
              type="select"
              value={filter.action}
              onChange={(e) =>
                setFilter({ ...filter, action: e.target.value })
              }
            >
              <option value="">Semua Aksi</option>
              <option value="CREATE">Buat</option>
              <option value="UPDATE">Ubah</option>
              <option value="DELETE">Hapus</option>
              <option value="VERIFY_TRANSACTION">Verifikasi</option>
              <option value="REJECT_TRANSACTION">Tolak</option>
              <option value="RESET_PASSWORD">Reset Password</option>
            </Input>
          </Col>
        </Row>

        <Row>
          <Col xl={12}>
            <Card>
              <CardHeader className="d-flex justify-content-between align-items-center">
                <h5 className="mb-0">
                  Riwayat Aktivitas ({pagination.total} aktivitas)
                </h5>
              </CardHeader>
              <CardBody>
                {loading ? (
                  <div className="text-center py-5">
                    <Spinner color="primary" />
                  </div>
                ) : (
                  <div className="table-responsive">
                    <Table className="table table-hover align-middle mb-0">
                      <thead className="table-light">
                        <tr>
                          <th>Waktu</th>
                          <th>Pengguna</th>
                          <th>Aksi</th>
                          <th>Entitas</th>
                          <th>ID Entitas</th>
                          <th>IP Address</th>
                        </tr>
                      </thead>
                      <tbody>
                        {logs.length > 0 ? (
                          logs.map((log) => (
                            <tr key={log.id}>
                              <td>{formatDateTime(log.createdAt)}</td>
                              <td>{log.user?.name || "System"}</td>
                              <td>
                                <span
                                  className={`badge bg-${getActionBadgeColor(
                                    log.action
                                  )}`}
                                >
                                  {log.action}
                                </span>
                              </td>
                              <td>{log.entityType}</td>
                              <td className="text-muted font-size-12">
                                {log.entityId?.substring(0, 8)}...
                              </td>
                              <td className="text-muted font-size-12">
                                {log.ipAddress || "-"}
                              </td>
                            </tr>
                          ))
                        ) : (
                          <tr>
                            <td
                              colSpan={6}
                              className="text-center text-muted py-4"
                            >
                              Tidak ada aktivitas dalam periode ini.
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </Table>
                  </div>
                )}

                {/* Pagination */}
                {pagination.totalPages > 1 && (
                  <div className="d-flex justify-content-between align-items-center mt-3">
                    <div>
                      Halaman {pagination.page} dari {pagination.totalPages}
                    </div>
                    <div className="d-flex gap-2">
                      <Button
                        color="secondary"
                        size="sm"
                        disabled={pagination.page === 1}
                        onClick={() =>
                          setPagination({ ...pagination, page: 1 })
                        }
                      >
                        First
                      </Button>
                      <Button
                        color="secondary"
                        size="sm"
                        disabled={pagination.page === 1}
                        onClick={() =>
                          setPagination({
                            ...pagination,
                            page: pagination.page - 1,
                          })
                        }
                      >
                        Prev
                      </Button>
                      <Button
                        color="secondary"
                        size="sm"
                        disabled={
                          pagination.page === pagination.totalPages
                        }
                        onClick={() =>
                          setPagination({
                            ...pagination,
                            page: pagination.page + 1,
                          })
                        }
                      >
                        Next
                      </Button>
                    </div>
                  </div>
                )}
              </CardBody>
            </Card>
          </Col>
        </Row>
      </div>
    </div>
  );
};

export default AuditPage;
