// parkirgo-admin/src/app/(parkirgo)/dashboard/page.tsx
"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { Card, CardBody, CardHeader, Col, Row, Spinner } from "reactstrap";
import ReactApexChart from "react-apexcharts";

const DashboardPage = () => {
  const [loading, setLoading] = useState(true);
  const [dashboardData, setDashboardData] = useState<any>(null);
  const [selectedDate, setSelectedDate] = useState(
    new Date().toISOString().split("T")[0]
  );

  useEffect(() => {
    fetchDashboardData();
  }, [selectedDate]);

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      const res = await fetch(`/api/dashboard?date=${selectedDate}`);
      const data = await res.json();
      if (data.success) {
        setDashboardData(data.data);
      }
    } catch (error) {
      console.error("Error fetching dashboard:", error);
    } finally {
      setLoading(false);
    }
  };

  // Chart options
  const weeklyChartOptions: any = {
    chart: {
      height: 280,
      type: "area",
      toolbar: {
        show: false,
      },
    },
    colors: ["#5664d2", "#22c55e"],
    dataLabels: {
      enabled: false,
    },
    stroke: {
      curve: "smooth",
      width: 2,
    },
    fill: {
      type: "gradient",
      gradient: {
        shadeIntensity: 1,
        opacityFrom: 0.3,
        opacityTo: 0.05,
        stops: [0, 90, 100],
      },
    },
    xaxis: {
      categories: dashboardData?.weeklyTrend?.map((d: any) => {
        const date = new Date(d.date);
        return date.toLocaleDateString("id-ID", { weekday: "short" });
      }) || [],
    },
    yaxis: {
      labels: {
        formatter: (val: number) => {
          return new Intl.NumberFormat("id-ID", {
            style: "currency",
            currency: "IDR",
            maximumFractionDigits: 0,
          }).format(val);
        },
      },
    },
    tooltip: {
      y: {
        formatter: (val: number) =>
          new Intl.NumberFormat("id-ID", {
            style: "currency",
            currency: "IDR",
            maximumFractionDigits: 0,
          }).format(val),
      },
    },
  };

  const weeklyChartSeries = [
    {
      name: "Pendapatan",
      data:
        dashboardData?.weeklyTrend?.map((d: any) => d.total) ||
        [0, 0, 0, 0, 0, 0, 0],
    },
  ];

  const paymentChartOptions: any = {
    chart: {
      type: "donut",
    },
    labels: ["Tunai", "QRIS"],
    colors: ["#5664d2", "#22c55e"],
    legend: {
      position: "bottom",
    },
    responsive: [
      {
        breakpoint: 480,
        options: {
          chart: {
            height: 200,
          },
          legend: {
            position: "bottom",
          },
        },
      },
    ],
    tooltip: {
      y: {
        formatter: (val: number) =>
          new Intl.NumberFormat("id-ID", {
            style: "currency",
            currency: "IDR",
            maximumFractionDigits: 0,
          }).format(val),
      },
    },
  };

  const paymentData = [
    dashboardData?.paymentBreakdown?.cash?._sum?.amount || 0,
    dashboardData?.paymentBreakdown?.qris?._sum?.amount || 0,
  ];

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <>
      <div className="page-content">
        <div className="container-fluid">
          {/* Page Title */}
          <div className="row">
            <div className="col-12">
              <div className="page-title-box d-flex align-items-center justify-content-between">
                <h4 className="mb-0 font-size-18">Dashboard ParkirGo</h4>
                <div className="page-title-right">
                  <input
                    type="date"
                    className="form-control form-control-sm"
                    style={{ width: "auto" }}
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e.target.value)}
                  />
                </div>
              </div>
            </div>
          </div>

          {loading ? (
            <div className="text-center py-5">
              <Spinner color="primary" />
              <p className="mt-2 text-muted">Memuat data dashboard...</p>
            </div>
          ) : (
            <>
              {/* Summary Cards */}
              <Row>
                <Col xl-3 md-6}>
                  <Card className="mini-stats-wid">
                    <CardBody>
                      <div className="d-flex">
                        <div className="flex-grow-1 overflow-hidden">
                          <p className="text-muted fw-medium text-truncate mb-0">
                            Pendapatan Hari Ini
                          </p>
                          <h4 className="mb-0 font-size-20 fw-semibold">
                            {formatCurrency(
                              dashboardData?.summary?.todayRevenue || 0
                            )}
                          </h4>
                        </div>
                        <div className="mini-stat-icon avatar-sm rounded-circle bg-primary align-self-center">
                          <span className="avatar-title bg-primary rounded-circle font-size-20">
                            <i className="ri-money-dollar-circle-line text-white"></i>
                          </span>
                        </div>
                      </div>
                    </CardBody>
                  </Card>
                </Col>

                <Col xl-3 md-6>
                  <Card className="mini-stats-wid">
                    <CardBody>
                      <div className="d-flex">
                        <div className="flex-grow-1 overflow-hidden">
                          <p className="text-muted fw-medium text-truncate mb-0">
                            Total Transaksi
                          </p>
                          <h4 className="mb-0 font-size-20 fw-semibold">
                            {dashboardData?.summary?.todayTransactions || 0}
                          </h4>
                        </div>
                        <div className="mini-stat-icon avatar-sm rounded-circle bg-success align-self-center">
                          <span className="avatar-title bg-success rounded-circle font-size-20">
                            <i className="ri-file-list-3-line text-white"></i>
                          </span>
                        </div>
                      </div>
                    </CardBody>
                  </Card>
                </Col>

                <Col xl-3 md-6>
                  <Card className="mini-stats-wid">
                    <CardBody>
                      <div className="d-flex">
                        <div className="flex-grow-1 overflow-hidden">
                          <p className="text-muted fw-medium text-truncate mb-0">
                            Kendaraan Aktif
                          </p>
                          <h4 className="mb-0 font-size-20 fw-semibold">
                            {dashboardData?.summary?.activeSessions || 0}
                          </h4>
                        </div>
                        <div className="mini-stat-icon avatar-sm rounded-circle bg-warning align-self-center">
                          <span className="avatar-title bg-warning rounded-circle font-size-20">
                            <i className="ri-car-line text-white"></i>
                          </span>
                        </div>
                      </div>
                    </CardBody>
                  </Card>
                </Col>

                <Col xl-3 md-6>
                  <Card className="mini-stats-wid">
                    <CardBody>
                      <div className="d-flex">
                        <div className="flex-grow-1 overflow-hidden">
                          <p className="text-muted fw-medium text-truncate mb-0">
                            Juru Parkir Aktif
                          </p>
                          <h4 className="mb-0 font-size-20 fw-semibold">
                            {dashboardData?.summary?.totalJukir || 0}
                          </h4>
                        </div>
                        <div className="mini-stat-icon avatar-sm rounded-circle bg-info align-self-center">
                          <span className="avatar-title bg-info rounded-circle font-size-20">
                            <i className="ri-user-location-line text-white"></i>
                          </span>
                        </div>
                      </div>
                    </CardBody>
                  </Card>
                </Col>
              </Row>

              {/* Charts */}
              <Row>
                <Col xl={8}>
                  <Card>
                    <CardHeader className="d-flex align-items-center">
                      <h5 className="mb-0">Tren Pendapatan Mingguan</h5>
                    </CardHeader>
                    <CardBody>
                      <ReactApexChart
                        options={weeklyChartOptions}
                        series={weeklyChartSeries}
                        type="area"
                        height={280}
                      />
                    </CardBody>
                  </Card>
                </Col>

                <Col xl={4}>
                  <Card>
                    <CardHeader className="d-flex align-items-center">
                      <h5 className="mb-0">Metode Pembayaran</h5>
                    </CardHeader>
                    <CardBody>
                      <ReactApexChart
                        options={paymentChartOptions}
                        series={paymentData}
                        type="donut"
                        height={280}
                      />
                    </CardBody>
                  </Card>
                </Col>
              </Row>

              {/* Top Zones */}
              <Row>
                <Col xl={12}>
                  <Card>
                    <CardHeader className="d-flex align-items-center justify-content-between">
                      <h5 className="mb-0">Performa Zona Parkir</h5>
                      <Link
                        href="/zona"
                        className="btn btn-sm btn-soft-secondary"
                      >
                        Lihat Semua
                        <i className="mdi mdi-arrow-right ms-1"></i>
                      </Link>
                    </CardHeader>
                    <CardBody>
                      <div className="table-responsive">
                        <table className="table table-hover align-middle mb-0">
                          <thead className="table-light">
                            <tr>
                              <th>Zona</th>
                              <th>Kota</th>
                              <th className="text-center">Total Kendaraan</th>
                              <th className="text-end">Total Pendapatan</th>
                            </tr>
                          </thead>
                          <tbody>
                            {dashboardData?.topZones?.length > 0 ? (
                              dashboardData.topZones.map((zone: any) => (
                                <tr key={zone.id}>
                                  <td>
                                    <Link
                                      href={`/zona/${zone.id}`}
                                      className="text-body fw-medium"
                                    >
                                      {zone.name}
                                    </Link>
                                  </td>
                                  <td>{zone.city || "-"}</td>
                                  <td className="text-center">
                                    {zone.totalVehicles}
                                  </td>
                                  <td className="text-end fw-semibold">
                                    {formatCurrency(zone.totalRevenue)}
                                  </td>
                                </tr>
                              ))
                            ) : (
                              <tr>
                                <td
                                  colSpan={4}
                                  className="text-center text-muted py-4"
                                >
                                  Tidak ada data zona
                                </td>
                              </tr>
                            )}
                          </tbody>
                        </table>
                      </div>
                    </CardBody>
                  </Card>
                </Col>
              </Row>

              {/* Quick Actions */}
              <Row className="mt-4">
                <Col xl={12}>
                  <Card>
                    <CardHeader>
                      <h5 className="mb-0">Aksi Cepat</h5>
                    </CardHeader>
                    <CardBody>
                      <div className="d-flex flex-wrap gap-2">
                        <Link
                          href="/zona/baru"
                          className="btn btn-outline-primary"
                        >
                          <i className="ri-add-circle-line me-1"></i>
                          Tambah Zona Baru
                        </Link>
                        <Link
                          href="/tarif/baru"
                          className="btn btn-outline-success"
                        >
                          <i className="ri-money-dollar-circle-line me-1"></i>
                          Atur Tarif Baru
                        </Link>
                        <Link
                          href="/pengguna/baru"
                          className="btn btn-outline-info"
                        >
                          <i className="ri-user-add-line me-1"></i>
                          Tambah Pengguna
                        </Link>
                        <Link
                          href="/laporan/harian"
                          className="btn btn-outline-warning"
                        >
                          <i className="ri-bar-chart-box-line me-1"></i>
                          Lihat Laporan
                        </Link>
                      </div>
                    </CardBody>
                  </Card>
                </Col>
              </Row>
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default DashboardPage;

// backend/resources/js/Pages/parkirgo/Dashboard.vue
<script>
import Layout from "@/Layouts/main.vue";
import PageHeader from "@/Components/page-header.vue";
import { Link, router } from "@inertiajs/vue3";
import { VueEcharts } from "vue3-echarts";

const currency = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });

export default {
  components: { Layout, PageHeader, Link, VueEcharts },
  props: {
    summary: { type: Object, default: () => ({}) },
    zones: { type: Array, default: () => [] },
    chartData: { type: Object, default: () => ({ labels: [], series: [] }) },
    recentSessions: { type: Array, default: () => [] },
    recentTransactions: { type: Array, default: () => [] },
    period: { type: String, default: "today" },
  },
  computed: {
    periodLabel() {
      return { today: "Hari Ini", week: "Minggu Ini", month: "Bulan Ini", year: "Tahun Ini" }[this.period] || "Hari Ini";
    },
    apexChartOptions() {
      return {
        chart: { height: 380, type: "line", zoom: { enabled: false }, toolbar: { show: false } },
        dataLabels: { enabled: true, style: { fontSize: '10px' } },
        stroke: { width: 3, curve: "smooth" },
        markers: { size: 5 },
        xaxis: { categories: this.chartData.labels, title: { text: "Waktu" } },
        yaxis: { title: { text: "Pendapatan (Rp)" }, labels: { formatter: (v) => this.moneyShort(v) } },
        legend: { position: "top", horizontalAlign: "center" },
        tooltip: { y: { formatter: (v) => this.money(v) } }
      };
    }
  },
  methods: {
    money(v) { return currency.format(Number(v || 0)); },
    moneyShort(v) {
      if (v >= 1000000) return (v / 1000000).toFixed(1) + ' jt';
      if (v >= 1000) return (v / 1000).toFixed(0) + ' rb';
      return v;
    },
    statusClass(s) {
      return { active: "success", paid: "success", unpaid: "warning", recorded: "info", verified: "primary", exited: "secondary", completed: "primary" }[s] || "dark";
    },
    duration(v) {
      if (!v && v !== 0) return "-";
      const m = Math.floor(v / 60);
      const s = v % 60;
      return m > 0 ? `${m}m ${s}s` : `${s}s`;
    },
    gaugeOption(active, capacity) {
      const pct = capacity ? (active / capacity) * 100 : 0;
      const color = pct > 90 ? "#f06548" : pct > 70 ? "#f7b84b" : "#0ab39c";
      return {
        series: [{
          type: "gauge",
          center: ["50%", "60%"],
          radius: "100%",
          startAngle: 200,
          endAngle: -20,
          min: 0,
          max: capacity || 100,
          progress: { show: true, width: 6, itemStyle: { color: color } },
          pointer: { show: true, length: '60%', width: 3, itemStyle: { color: color } },
          axisLine: { lineStyle: { width: 6, color: [[1, "#e9ebec"]] } },
          axisTick: { show: false },
          splitLine: { show: false },
          axisLabel: { show: false },
          detail: { show: false },
          data: [{ value: active || 0 }]
        }]
      };
    },
    switchPeriod(p) {
      router.get("/", { period: p }, { preserveState: true });
    },
  },
};
</script>

<template>
  <Layout>
    <PageHeader title="Dashboard" pageTitle="ParkirGo" />

    <BCard no-body class="border-0 shadow-sm mb-4">
      <BCardBody class="py-2">
        <div class="d-flex flex-wrap gap-1" role="group">
          <button type="button" class="btn btn-sm" :class="period === 'today' ? 'btn-primary' : 'btn-soft-primary'" @click="switchPeriod('today')">Hari Ini</button>
          <button type="button" class="btn btn-sm" :class="period === 'week' ? 'btn-primary' : 'btn-soft-primary'" @click="switchPeriod('week')">Minggu Ini</button>
          <button type="button" class="btn btn-sm" :class="period === 'month' ? 'btn-primary' : 'btn-soft-primary'" @click="switchPeriod('month')">Bulan Ini</button>
          <button type="button" class="btn btn-sm" :class="period === 'year' ? 'btn-primary' : 'btn-soft-primary'" @click="switchPeriod('year')">Tahun Ini</button>
        </div>
      </BCardBody>
    </BCard>

    <BRow class="g-3 mb-4">
      <BCol xl="3" md="6">
        <BCard no-body class="border-0 overflow-hidden parkirgo-hero-card text-white">
          <BCardBody>
            <div class="d-flex align-items-start justify-content-between">
              <div>
                <p class="text-white-75 mb-2">Pendapatan {{ periodLabel }}</p>
                <h3 class="text-white mb-1">{{ money(summary.revenue_period) }}</h3>
                <span class="badge bg-white text-success">Live Ops</span>
              </div>
              <div class="avatar-sm rounded-circle bg-white bg-opacity-25 d-flex align-items-center justify-content-center">
                <i class="ri-wallet-3-line fs-22"></i>
              </div>
            </div>
          </BCardBody>
        </BCard>
      </BCol>
      <BCol xl="3" md="6">
        <BCard no-body class="border-0 shadow-sm">
          <BCardBody>
            <div class="d-flex justify-content-between">
              <div>
                <p class="text-muted mb-1">Sesi Aktif</p>
                <h3 class="mb-0">{{ summary.active_sessions || 0 }}</h3>
              </div>
              <div class="avatar-sm rounded-circle bg-primary-subtle text-primary d-flex align-items-center justify-content-center">
                <i class="ri-parking-box-line fs-22"></i>
              </div>
            </div>
          </BCardBody>
        </BCard>
      </BCol>
      <BCol xl="3" md="6">
        <BCard no-body class="border-0 shadow-sm">
          <BCardBody>
            <div class="d-flex justify-content-between">
              <div>
                <p class="text-muted mb-1">Jukir Online</p>
                <h3 class="mb-0">{{ summary.jukirs_online || 0 }}</h3>
              </div>
              <div class="avatar-sm rounded-circle bg-info-subtle text-info d-flex align-items-center justify-content-center">
                <i class="ri-user-smile-line fs-22"></i>
              </div>
            </div>
          </BCardBody>
        </BCard>
      </BCol>
      <BCol xl="3" md="6">
        <BCard no-body class="border-0 shadow-sm">
          <BCardBody>
            <div class="d-flex justify-content-between">
              <div>
                <p class="text-muted mb-1">Zona Aktif</p>
                <h3 class="mb-0">{{ summary.zones_active || 0 }}</h3>
              </div>
              <div class="avatar-sm rounded-circle bg-success-subtle text-success d-flex align-items-center justify-content-center">
                <i class="ri-map-pin-2-line fs-22"></i>
              </div>
            </div>
          </BCardBody>
        </BCard>
      </BCol>
    </BRow>

    <BRow class="mb-4">
      <BCol lg="12">
        <BCard no-body class="border-0 shadow-sm">
          <BCardHeader>
            <BCardTitle class="mb-0">Tren Pendapatan per Zona ({{ periodLabel }})</BCardTitle>
          </BCardHeader>
          <BCardBody>
            <apexchart
              class="apex-charts"
              height="380"
              dir="ltr"
              :series="chartData.series"
              :options="apexChartOptions"
            ></apexchart>
          </BCardBody>
        </BCard>
      </BCol>
    </BRow>

    <BRow class="g-3 mb-4">
      <BCol v-for="zone in zones" :key="zone.id" xl="4" md="6">
        <BCard no-body class="border-0 shadow-sm h-100 zone-card">
          <BCardBody>
            <div class="d-flex justify-content-between align-items-start mb-3">
              <div>
                <h5 class="mb-0 fw-bold">{{ zone.name }}</h5>
                <span class="badge bg-primary-subtle text-primary">{{ zone.code }}</span>
                <span v-if="zone.city" class="ms-1 text-muted small">{{ zone.city }}</span>
              </div>
              <span class="badge bg-success-subtle text-success">{{ zone.status }}</span>
            </div>

            <div class="table-responsive mb-3">
              <table class="table table-sm table-borderless align-middle mb-0 text-center">
                <thead>
                  <tr class="text-muted small border-bottom">
                    <th class="pb-1">PENDAPATAN</th>
                    <th class="pb-1">KENDARAAN</th>
                    <th class="pb-1">JUKIR</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="pt-2">
                      <h4 class="fw-bold text-success mb-0">{{ money(zone.revenue_sum) }}</h4>
                    </td>
                    <td class="pt-2">
                      <h4 class="fw-semibold mb-0">{{ zone.parkir_out_count || 0 }}</h4>
                    </td>
                    <td class="pt-2">
                      <h4 class="fw-semibold mb-0">{{ zone.jukirs_count || 0 }}</h4>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <hr class="my-3" />

            <div class="d-flex" style="gap:1px;overflow-x:auto">
              <div v-for="vt in zone.vehicle_types" :key="vt.id" class="text-center flex-fill px-1">
                <i :class="vt.icon || 'ri-car-line'" class="fs-22 d-block mb-1 text-primary"></i>
                <span class="small fw-medium d-block text-truncate" style="max-width:80px">{{ vt.name }}</span>
                <div class="d-flex justify-content-center" style="height:55px">
                  <VueEcharts :option="gaugeOption(vt.active_count, vt.pivot.capacity)" style="width:65px;height:55px" />
                </div>
                <div class="small fw-semibold mt-1">{{ vt.active_count || 0 }}<span class="text-muted fw-normal">/{{ vt.pivot.capacity }}</span></div>
                <div class="small" :class="(vt.pivot.capacity - vt.active_count) > 0 ? 'text-success' : 'text-danger'">
                  {{ Math.max(0, vt.pivot.capacity - vt.active_count) }} sisa
                </div>
              </div>
            </div>
          </BCardBody>
        </BCard>
      </BCol>
    </BRow>

    <BRow>
      <BCol xl="6">
        <BCard no-body class="border-0 shadow-sm mb-3">
          <BCardHeader>
            <BCardTitle class="mb-0">Transaksi Terbaru</BCardTitle>
          </BCardHeader>
          <BCardBody>
            <template v-if="recentTransactions.length">
              <div v-for="trx in recentTransactions" :key="trx.id" class="d-flex align-items-center border-bottom pb-3 mb-3">
              <div class="avatar-xs me-3 rounded-circle bg-info-subtle text-info d-flex align-items-center justify-content-center">
                <i class="ri-bank-card-line"></i>
              </div>
              <div class="flex-grow-1">
                <h6 class="mb-1">{{ trx.transaction_number }}</h6>
                <p class="text-muted mb-0">{{ trx.zone?.name }} · {{ trx.payment_method }}</p>
              </div>
              <div class="text-end">
                <div class="fw-semibold">{{ money(trx.amount) }}</div>
                <span class="badge" :class="`bg-${statusClass(trx.status)}-subtle text-${statusClass(trx.status)}`">{{ trx.status }}</span>
              </div>
            </div>
            </template>
            <div v-if="!recentTransactions.length" class="text-center text-muted py-3">Belum ada transaksi.</div>
          </BCardBody>
        </BCard>
      </BCol>
      <BCol xl="6">
        <BCard no-body class="border-0 shadow-sm mb-3">
          <BCardHeader>
            <BCardTitle class="mb-0">Sesi Aktif Terbaru</BCardTitle>
          </BCardHeader>
          <BCardBody>
            <template v-if="recentSessions.length">
              <div v-for="session in recentSessions" :key="session.id" class="d-flex align-items-center border-bottom pb-3 mb-3">
              <div class="avatar-xs me-3 rounded-circle bg-primary-subtle text-primary d-flex align-items-center justify-content-center">
                <i class="ri-parking-box-line"></i>
              </div>
              <div class="flex-grow-1">
                <h6 class="mb-1">{{ session.ticket_number }}</h6>
                <p class="text-muted mb-0">{{ session.zone?.name }} · {{ session.plate_number }}</p>
              </div>
              <div class="text-end">
                <div class="small">{{ duration(session.duration_minutes) }}</div>
                <span class="badge" :class="`bg-${statusClass(session.status)}-subtle text-${statusClass(session.status)}`">{{ session.status }}</span>
              </div>
            </div>
            </template>
            <div v-if="!recentSessions.length" class="text-center text-muted py-3">Belum ada sesi.</div>
          </BCardBody>
        </BCard>
      </BCol>
    </BRow>
  </Layout>
</template>

<style scoped>
.parkirgo-hero-card {
  background: linear-gradient(135deg, #0f9f6e, #0ea5e9 55%, #4f46e5);
  box-shadow: 0 18px 45px rgba(14, 165, 233, 0.22);
}
.text-white-75 { color: rgba(255,255,255,.75); }
.zone-card { transition: transform .2s ease, box-shadow .2s ease; border-radius: 12px; }
.zone-card:hover { transform: translateY(-4px); box-shadow: 0 18px 45px rgba(15, 23, 42, .12) !important; }
.avatar-xs { width: 32px; height: 32px; object-fit: cover; }
</style>
